chatting/config/routes.rb
Rails.application.routes.draw do
  resources :people
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show]

  get "/park" => "taipei_park#park"
  get "/aboutus" => "aboutus#aboutus"

  resources :topics do
    resources :comments
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end
  end

  resources :users do
    resource :profile, :controller => :'user_profiles'
  end

   root 'topics#index'

end

chatting/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
end

chatting/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates_presence_of :content
  belongs_to :topic, :counter_cache => true


  belongs_to :user
end

chatting/app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :topic
  belongs_to :user


end

chatting/app/models/park.rb
class Park < ActiveRecord::Base
end

chatting/app/models/person.rb
class Person < ActiveRecord::Base
end

chatting/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

chatting/app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user
  belongs_to :topic

end

chatting/app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :topic_taggers
  has_many :topics, :through => :topic_taggers

end

chatting/app/models/topic.rb
class Topic < ActiveRecord::Base

  STATUS = ["draft", "published", "scheduled" ]

  validates_presence_of :subject



  belongs_to :user
  belongs_to :category

  has_many :comments

  has_many :likes
  has_many :like_users, :through => :likes, :source => :user

  has_many :subscriptions
  has_many :subscribed_users, :through => :likes, :source => :user

  has_many :topic_taggers
  has_many :tags, :through => :topic_taggers

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def finy_like_by(user)
    user && self.likes.find_by_user_id( user.id )
  end

  def finy_subscription_by(user)
    user && self.subscriptions.find_by_user_id( user.id )
  end

end

chatting/app/models/topic_tagger.rb
class TopicTagger < ActiveRecord::Base

  belongs_to :topic
  belongs_to :tag
end

chatting/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :topics
  has_many :comments
  has_one :profile

  has_many :likes
  has_many :like_topics, :through => :likes, :source => :topic

  has_many :subscriptions
  has_many :subscribed_topics, :through => :subscriptions, :source => :topic


  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

  def display_name
    self.email.split('@').first
  end

end

chatting/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic

  def create
    like = @topic.finy_like_by(current_user)

    if like

    else
     @like =  @topic.likes.create!( :user => current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render "like" }
    end
  end

  def destroy
    @like = current_user.likes.find( params[:id] )
    @like.destroy

    @like = nil

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render "like" }
    end
  end

  protected

  def set_topic
    @topic = Topic.find( params[:topic_id] )
  end

end

chatting/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_my_topic, :only => [:edit, :update, :destroy]

  def index

      @q = Topic.ransack(params[:q])

      @topics = @q.result(distinct: true)

      if params[:sort] == "by ID"
         @topics = @topics.order("id")
      elsif params[:sort] == "by time"
        @topics = @topics.order("updated_at DESC")
      elsif params[:sort] == "by replies"
        @topics = @topics.order("comments_count")
      elsif params[:sort] == "by categories"
        @topics = Category.find(params[:category_id]).topics
      else
        @topics = @topics.order("id DESC")
      end

      @topics = @topics.where( :status => "published" )
      @topics = @topics.page(params[:page]).per(10)

        respond_to do |format|
          format.html
          format.js
        end

    end

  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new
    @users = User.where(:id =>@topic.likes.pluck(:user_id))


    unless cookies["view-topic=#{@topic.id}"]
      cookies["view-topic-#{@topic.id}"] = "viewed"
      @topic.views_count += 1
      @topic.save!
    end

  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new( topic_params )
    @topic.user = current_user
    if @topic.save
      redirect_to topic_url(@topic)
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @topic.destroy
    redirect_to topics_url
  end

  def update
    if params[:destory_image]
      @topic.image = nil
    end

    if @topic.update( topic_params )
      redirect_to topic_url(@topic)
    else
      render "edit"
    end
  end

  def subscribe
    @topic = Topic.find( params[:id] )
    @topic.subscriptions.create!( :user => current_user)
    # subscription = @topic.finy_subscription_by(current_user)
    # if subscription
    # else
      # @subscription = @topic.subscriptions.create!( :user => current_user)
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js
    end
  end
    # redirect_to :back
  # end

  def unsubscribe
    @topic = Topic.find( params[:id] )
    current_user.subscriptions.where( :topic_id => @topic.id ).destroy_all

    # subscription = @topic.finy_subscription_by(current_user)
    # subscription.destroy

    # redirect_to :back
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js { render "subscribe"}
    end
  end



  protected

  def topic_params
    params.require(:topic).permit(:content, :subject, :image, :category_id, :status, :tag_ids => [])
  end

  def set_my_topic
    @topic = Topic.find( params[:id])
  end

end

chatting/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @user_topics = @user.topics
    @comments = @user.comments
    @topics = Topic.where(:id => @user.likes.pluck(:topic_id))
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update( user_params )
      redirect_to root_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:time_zone)
  end

end

chatting/app/helpers/aboutus_helper.rb
module AboutusHelper
end

chatting/app/helpers/application_helper.rb
module ApplicationHelper
end

chatting/app/helpers/comments_helper.rb
module CommentsHelper
end

chatting/app/helpers/likes_helper.rb
module LikesHelper
end

chatting/app/helpers/people_helper.rb
module PeopleHelper
end

chatting/app/helpers/taipei_park_helper.rb
module TaipeiParkHelper
end

chatting/app/helpers/topics_helper.rb
module TopicsHelper

  def topic_status_options

    Topic::STATUS.map do |status|
      [ t(status, :scope => "topic.status"), status ]
    end

  end

  def category_name_options
    Category.all.map do |c|
      [c.name, c.id ]
    end
  end


end

chatting/app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

chatting/app/helpers/users_helper.rb
module UsersHelper
end

chatting/app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
   <% @topic.errors.full_messages.each do |m| %>
   <p><%= m %></p>
   <% end %>
<% end %>

<%= form_for @topic do |f| %>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, topic_status_options, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%#= f.collection_select :category_id, Category.all, :id, :name, {}, :class => "form-control" %>
    <%= f.select :category_id, category_name_options, {}, :class => "form-control" %>
    </div>

  <div class ="form-group">

    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, :class => "form-control" %>

    <% if @topic.image.exists? %>
      <%= check_box_tag "destory_image", "1" %> 刪除圖片
    <% end %>

  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

<script>

$("#topic_category_id" ).select2({
  theme: "bootstrap"
});

</script>

chatting/app/views/topics/_like.html.erb
<h2><%= @topic.likes.count %></h2>
<% if like %>
  <%= link_to "Unlike", topic_like_path(@topic, like), :remote => true, :method => :delete, :class => "btn btn-primary btn-sm" %>
<% else %>
  <%= link_to "Like", topic_likes_path(@topic), :remote => true, :method => :post, :class => "btn btn-primary btn-sm" %>
<% end %>

chatting/app/views/topics/_subscribe.html.erb
<% subscription = @topic.finy_subscription_by(current_user) %>
<% if subscription %>
  <%= link_to "Unsubscribe", unsubscribe_topic_path(@topic), :method => :post, :remote => true, :class => "btn btn-primary btn-sm" %>
  <% else %>
  <%= link_to "Subscribe", subscribe_topic_path(@topic), :method => :post, :remote => true, :class => "btn btn-primary btn-sm" %>
  <% end %>

chatting/app/views/topics/_topic.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :subject_cont, "Search Articles by Topic Keywords" %>
  <%= f.search_field :subject_cont %>
  <%= f.submit "Search" %>
<% end %>

<p><h3>
  <%= sort_link(@q, :id, "by ID") %> |
  <%= sort_link(@q, :updated_at, "by time") %> |
  <%= sort_link(@q, :comments_count, "by replies") %> |
  <%= sort_link(@q, :category_id, "by categories") %>
</p></h3>
  <table class = "table table-bordered table-striped text-center">
    <tr>
      <th><h3>Title</h3></th>
      <th><h3>Category</h3></th>
      <th><h3>Author</h3></th>
      <th><h3>Time</h3></th>
      <th><h3>Views</h3></th>
      <th><h3>Comments</h3></th>
    </tr>

  <h2><% @topics.each do |p| %>
    <tr>
      <td><%= link_to p.subject, topic_path(p) %></td>
      <td><%= p.category.try(:name) %></td>
      <td><%= link_to p.user.try(:display_name),user_path(p.user.id) %></td>
      <td><%= p.created_at.to_s(:short) %></td>
      <td><%= p.views_count %></td>
      <td><%= p.comments.size %></td>
    </tr>
  <% end %> </h2>
</table>

chatting/app/views/topics/edit.html.erb
<%= render "form" %>

chatting/app/views/topics/index.html.erb
<h1><p class = "text-center">I'm your worst nightmare.</p></h1>

<div id= "topics-pagination">
<%= paginate @topics, remote: true %>
</div>

<div id="topics-page">
  <%= render :partial => "topic" %>
</div>

chatting/app/views/topics/index.js.erb
$("#topics-page").html(
  "<%= escape_javascript(render :partial => "topic") %>"
  );

$("#topics-pagination").html(
  "<%= escape_javascript(paginate @topics, remote: true) %>"
  );

chatting/app/views/topics/new.html.erb
<%= form_for @topic do |f| %>
<div class = "form = group">

<div class="form-group">
  <%= f.label :subject %>
  <%= f.text_field :subject, :class => "form-control" %>
</div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

chatting/app/views/topics/show.html.erb
<h1><%= @topic.subject %></h1>

<% like = @topic.finy_like_by(current_user) %>
<div id="like-area">
  <%= render :partial => "like", :locals => { :like => like} %>

<% @users.each do |t| %>
  who liked this articles: <%= t.display_name %>
  <% end %>
</div>

<p></p>

<span id= "subscript-block" %>
<%= render "subscribe" %>
</span>


<% if @topic.image.exists? %>
  <%= link_to @topic.image.url, :target => "_blank" do %>
    <%= image_tag(@topic.image.url(:thumb)) %>
  <% end %>
<% end %>

<h2>Status: <%= t( @topic.status, :scope => "topic.status" ) %></h2>

<h2>Category: <%= @topic.category.try(:name) %></h2>

<% @topic.tags.each do |tag| %>
  <%= tag.name %>
  <% end %>



<%= simple_format @topic.content %>

<%= form_for [@topic, @comment], :remote => true do |f| %>

  <% if @comment.errors.any? %>
     <% @comment.errors.full_messages.each do |m| %>
     <p><%= m %></p>
     <% end %>
  <% end %>

  <%= link_to "edit", edit_topic_path(@topic),:class => "btn btn-info" %>
  <%= link_to "delete", topic_path(@topic),:class => "btn btn-danger", :method => :delete, data: {confirm: "你確定要刪除此心情分享嗎？"} %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-warning" %>
  </div>
<% end %>

<div id="count">
<%= render :partial => "comments/count", :locals => { :topic => @topic } %>
</div>
<h2>留言回覆</h2>
<ul id="comments-list">

<% @topic.comments.order("id DESC").each do |c| %>

<%= render :partial => "comments/comment", :locals => {:c => c } %>

<% end %>
</ul>

chatting/app/views/topics/subscribe.js.erb
$("#subscript-block").html("<%=j render(:partial => "subscribe") %>");