chatting/config/routes.rb
Rails.application.routes.draw do
  resources :people
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show]

  get "/park" => "taipei_park#park"
  get "/aboutus" => "aboutus#aboutus"

  resources :topics do
    resources :comments
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end
  end

  resources :users do
    resource :profile, :controller => :'user_profiles'
  end

   root 'topics#index'

end

chatting/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
end

chatting/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates_presence_of :content
  belongs_to :topic, :counter_cache => true


  belongs_to :user
end

chatting/app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :topic
  belongs_to :user


end

chatting/app/models/park.rb
class Park < ActiveRecord::Base
end

chatting/app/models/person.rb
class Person < ActiveRecord::Base
end

chatting/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

chatting/app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user
  belongs_to :topic

end

chatting/app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :topic_taggers
  has_many :topics, :through => :topic_taggers

end

chatting/app/models/topic.rb
class Topic < ActiveRecord::Base

  STATUS = ["draft", "published", "scheduled" ]

  validates_presence_of :subject



  belongs_to :user
  belongs_to :category

  has_many :comments

  has_many :likes
  has_many :like_users, :through => :likes, :source => :user

  has_many :subscriptions
  has_many :subscribed_users, :through => :likes, :source => :user

  has_many :topic_taggers
  has_many :tags, :through => :topic_taggers

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def finy_like_by(user)
    user && self.likes.find_by_user_id( user.id )
  end

  def finy_subscription_by(user)
    user && self.subscriptions.find_by_user_id( user.id )
  end

end

chatting/app/models/topic_tagger.rb
class TopicTagger < ActiveRecord::Base

  belongs_to :topic
  belongs_to :tag
end

chatting/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :topics
  has_many :comments
  has_one :profile

  has_many :likes
  has_many :like_topics, :through => :likes, :source => :topic

  has_many :subscriptions
  has_many :subscribed_topics, :through => :subscriptions, :source => :topic


  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

  def display_name
    self.email.split('@').first
  end

end

chatting/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic

  def create
    like = @topic.finy_like_by(current_user)

    if like

    else
     @like =  @topic.likes.create!( :user => current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render "like" }
    end
  end

  def destroy
    @like = current_user.likes.find( params[:id] )
    @like.destroy

    @like = nil

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render "like" }
    end
  end

  protected

  def set_topic
    @topic = Topic.find( params[:topic_id] )
  end

end

chatting/app/helpers/aboutus_helper.rb
module AboutusHelper
end

chatting/app/helpers/application_helper.rb
module ApplicationHelper
end

chatting/app/helpers/comments_helper.rb
module CommentsHelper
end

chatting/app/helpers/likes_helper.rb
module LikesHelper
end

chatting/app/helpers/people_helper.rb
module PeopleHelper
end

chatting/app/helpers/taipei_park_helper.rb
module TaipeiParkHelper
end

chatting/app/helpers/topics_helper.rb
module TopicsHelper

  def topic_status_options

    Topic::STATUS.map do |status|
      [ t(status, :scope => "topic.status"), status ]
    end

  end

  def category_name_options
    Category.all.map do |c|
      [c.name, c.id ]
    end
  end


end

chatting/app/helpers/users_helper.rb
module UsersHelper
end

chatting/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloody_Mary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Nosifer' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Fredericka+the+Great|League+Script' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ="container">
<h1><p class = "text-right"><%= link_to "Click Me to Go Home ಠ_ಠ", root_path %></p></h1>
<p class = "text-right">| <%= link_to "Taipei Park Info", park_path, :class => "btn btn-primary btn-md" %> |
<%= link_to "About Us", aboutus_path, :class => "btn btn-primary btn-md" %> |</p>
<p></p>
<h3><% if current_user %>
<%= t(:hi, :name => current_user.display_name ) %>
<p></p>
<%= t("admin.foo") %>
<%= t("admin.bar") %></h3>
<%= t("admin", :scope => "foo") %>

<% end %>



<% if current_user %>
         <p class = "text-right">| <%= link_to "Share Stories", new_topic_path, :class => "btn btn-default btn-sm" %> |
         <%= link_to( t(:change_password) , edit_registration_path(:user), :class => "btn btn-danger btn-sm") %> |
         <%= link_to "Setting", edit_registration_path(:user), :class => "btn btn-danger btn-sm" %> |
         <%= link_to " Edit Profile", edit_user_path(current_user), :class => "btn btn-danger btn-sm" %> |
         <%= link_to( t(:logout), destroy_user_session_path, :class => "btn btn-default btn-sm", :method => :delete) %> |
     <% else %>
         <%= link_to('Sign-up', new_registration_path(:user), :class => "btn btn-default btn-sm") %> |
         <%= link_to('Login', new_session_path(:user), :class => "btn btn-primary btn-sm") %> |
         <%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook), :class => "btn btn-primary btn-sm" %>

     <% end %>


     <p style="color: green"><%= flash[:notice] %></p>
     <p style="color: red"><%= flash[:alert] %></p>

      <div class="centered">
       <%= image_tag("speechless.png") %>
       <%= image_tag("speechless.png") %>
       <%= image_tag("speechless.png") %>

       </div>

<%= yield %>
    </div>
  </div>
</div>
<p class="text-center">
  <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %> |
  <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
</p>
  <h3><p class="text-center"> | <%= link_to "Click Me to Go Home ಠ_ಠ", root_path %> | <%= link_to "Click Me to Go Home ಠ_ಠ", root_path %> | <%= link_to "Click Me to Go Home ಠ_ಠ", root_path %> |</p></h3>

</body>
</html>